/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmailValid;
import controllers.FileStream;
import models.People;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOAN
 */
public class NewPeople extends javax.swing.JFrame {

    ArrayList<People> pList = new ArrayList<>();
    EmailValid checkMail = new EmailValid("\\w+@\\w+(\\.\\w+)+");

    public NewPeople() {
        initComponents();

        this.setLocation(470, 220);
        this.setResizable(false);
        
        JRootPane rootPane = SwingUtilities.getRootPane(btnAdd);
        rootPane.setDefaultButton(btnAdd);
        
        setDefault();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        vali1 = new javax.swing.JLabel();
        vali2 = new javax.swing.JLabel();
        vali3 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setTitle("Add People");
        setAlwaysOnTop(true);

        btnAdd.setText("AddNew");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("User name:");

        jLabel2.setText("Full name:");

        jLabel3.setText("Email address:");

        vali1.setText("(*)");

        vali2.setText("(*)");

        vali3.setText("(*)");

        lblStatus.setText("* Những field có dấu (*) là bắt buộc.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel))
                            .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtUserName)
                            .addComponent(txtEmailAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vali1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vali2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vali3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(vali1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(vali2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(vali3))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String user = txtUserName.getText().trim();
        String fullName = txtFullName.getText().trim();
        String email = txtEmailAddress.getText().trim();

        if (!user.equals("") && fullName.equals("") && email.equals("")) {
            lblStatus.setText("* Full Name, Email empty..");
            setDefault();
            vali2.setForeground(Color.RED);
            vali3.setForeground(Color.RED);
            lblStatus.setForeground(Color.RED);
        }
        else if (user.equals("") && !fullName.equals("") && !email.equals("")) {
            lblStatus.setText("* User empty..");
            setDefault();
            vali1.setForeground(Color.RED);
            lblStatus.setForeground(Color.RED);
        }
        else if (user.equals("") && !fullName.equals("") && email.equals("")) {
            lblStatus.setText("* User, Email empty..");
            setDefault();
            vali1.setForeground(Color.RED);
            vali3.setForeground(Color.RED);
            lblStatus.setForeground(Color.RED);
        }
        else if (!user.equals("") && fullName.equals("") && !email.equals("")) {
            lblStatus.setText("* Full Name empty..");
            setDefault();
            vali2.setForeground(Color.RED);
            lblStatus.setForeground(Color.RED);
        }
        else if (user.equals("") && fullName.equals("") && !email.equals("")) {
            lblStatus.setText("* User, Full name empty..");
            setDefault();
            vali1.setForeground(Color.RED);
            vali2.setForeground(Color.RED);
            lblStatus.setForeground(Color.RED);
        }
        else if (!user.equals("") && !fullName.equals("") && email.equals("")) {
            lblStatus.setText("* Email empty..");
            setDefault();
            vali3.setForeground(Color.RED);
            lblStatus.setForeground(Color.RED);
        } else if (!user.equals("") && !fullName.equals("") && !email.equals("")) {
            if (checkMail.validate(email)) {
                People p = new People(txtUserName.getText(), txtFullName.getText(), txtEmailAddress.getText());
                pList.add(p);
                FileStream.writeFile(pList);
                int count = AppMain.tblPeople.getRowCount();

                DefaultTableModel model = (DefaultTableModel) AppMain.tblPeople.getModel();
                model.addRow(new Object[]{
                    " " + ++count, " " + txtUserName.getText(), " " + txtFullName.getText(), " " + txtEmailAddress.getText()
                });

                this.setVisible(false);
            } else {
                lblStatus.setText("* Wrong Email..");
                setDefault();
                vali3.setForeground(Color.RED);
                lblStatus.setForeground(Color.RED);
            }
        } else {
            lblStatus.setText("* User, Full name, Email empty..");
            setRed();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    public void setDefault() {
        lblStatus.setForeground(Color.gray);
        vali1.setForeground(Color.gray);
        vali2.setForeground(Color.gray);
        vali3.setForeground(Color.gray);
    }

    public void setRed() {
        lblStatus.setForeground(Color.RED);
        vali1.setForeground(Color.RED);
        vali2.setForeground(Color.RED);
        vali3.setForeground(Color.RED);
    }

    public void setClean() {
        txtUserName.setText("");
        txtFullName.setText("");
        txtEmailAddress.setText("");

        vali1.setForeground(Color.BLACK);
        vali2.setForeground(Color.BLACK);
        vali3.setForeground(Color.BLACK);
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPeople.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPeople().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JLabel vali1;
    private javax.swing.JLabel vali2;
    private javax.swing.JLabel vali3;
    // End of variables declaration//GEN-END:variables
}
